- name: create project
  file:
    path: "{{ansible_root}}/{{project_name}}.yml"
    state: touch
  tags: create_project

- name: create roles dir
  file:
    path: "{{ansible_root}}/roles/{{project_name}}"
    state: directory
  tags: create_roles

- name: create sub directorie
  file:
    path: "{{ansible_root}}/roles/{{project_name}}/{{item}}"
    state: directory
  loop:
    - defaults
    - tasks
    - meta
    - handlers
    - files
    - vars
    - templates
  tags: create_sub

- name: create main yaml files
  file:
    path: "{{ansible_root}}/roles/{{project_name}}/{{item}}/main.yml"
    state: touch
  loop:
    - tasks
    - vars
    - handlers
    - meta
    - defaults
    - templates
  tags: create_yml


